name: Run Maestro Tests

on:
  push:
    branches:
      - main  # Run tests on pushes to the main branch
  pull_request:  # Run tests on pull requests
    branches:
      - main

jobs:
  maestro-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Maestro CLI
        run: |
          curl -fsSL "https://get.maestro.mobile.dev" | bash
          echo "$HOME/.maestro/bin" >> $GITHUB_PATH

      - name: Set up Android environment
        uses: android-actions/setup-android@v3

      - name: Start Android Emulator
        run: |
          echo "Starting Android Emulator..."
          nohup emulator -avd test -no-snapshot-save -noaudio -no-window -gpu swiftshader_indirect -no-boot-anim &
          adb wait-for-device
          adb shell settings put global window_animation_scale 0
          adb shell settings put global transition_animation_scale 0
          adb shell settings put global animator_duration_scale 0
        timeout-minutes: 5

      - name: Verify Emulator is Running
        run: adb devices

      - name: Run Maestro Tests
        run: maestro test maestro_flows/flows.yaml --output report.xml

      - name: Upload Maestro Test Report
        uses: actions/upload-artifact@v4
        with:
          name: maestro-report
          path: ./report.xml